apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-podinfo-dev
  name: nginx-podinfo-dev
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-podinfo-dev
  template:
    metadata:
      name: nginx-podinfo-dev
      labels:
        app: nginx-podinfo-dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: install
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: busybox
          command:
            - sh
            - -c
            - echo "POD_NAME:${POD_NAME} POD_IP:${POD_IP} branch:dev" > /work-dir/index.html
          volumeMounts:
            - name: workdir
              mountPath: "/work-dir"
      volumes:
        - name: workdir
          emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-podinfo-dev
  namespace: default
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-podinfo-dev
  type: ClusterIP